-- Create services table
create table if not exists services (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  price numeric,
  details text,
  deliverables jsonb,
  timeline text
);

-- Create bundles table
create table if not exists bundles (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  serviceIds jsonb, -- Storing array of IDs as JSONB
  discount numeric,
  price numeric
);

-- Create ui_settings table
create table if not exists ui_settings (
  id bigint generated by default as identity primary key,
  site_title text,
  site_subtitle text,
  logo_url text,
  badge_url text,
  intro_video_id text,
  intro_text text,
  checkout_button_text text,
  catalog_title text,
  catalog_subtitle text,
  -- Hero section fields
  hero_headline text,
  hero_subheadline text,
  hero_badge1_title text,
  hero_badge1_subtitle text,
  hero_badge2_title text,
  hero_badge2_subtitle text,
  hero_badge3_title text,
  hero_badge3_subtitle text
);

-- Insert default settings if not exists
insert into ui_settings (id, site_title, site_subtitle, logo_url, badge_url, intro_text, checkout_button_text, catalog_title, catalog_subtitle)
values (1, 'Build Your Growth Stack', 'Select the HubSpot jobs you need. No retainers. Just results.', 'https://goenvy.io/wp-content/uploads/2022/10/ENVY-Logo.svg', 'https://l.goenvy.io/hubfs/elite.svg', 'We help businesses grow with expert HubSpot services. No long-term commitments, just results.', 'Request Consultation', 'Job Catalog', 'Browse all available HubSpot jobs and their details')
on conflict (id) do nothing;

-- Enable Row Level Security (RLS)
alter table services enable row level security;
alter table bundles enable row level security;
alter table ui_settings enable row level security;

-- Create policies to allow public access
-- NOTE: This allows anyone with the API key to read/write. 
-- For production, you should restrict write access to authenticated users.
create policy "Public Access Services" on services for all using (true) with check (true);
create policy "Public Access Bundles" on bundles for all using (true) with check (true);
create policy "Public Access Settings" on ui_settings for all using (true) with check (true);
